// <auto-generated />
namespace UniversityCourseAndResultManagmentSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class varsoin6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(varsoin6));
        
        string IMigrationMetadata.Id
        {
            get { return "201703140920303_varsoin6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
